### ISSUE TITLE
Cannot install latest version on Linux

### ISSUE THREAD

**Issue by jpalumickas** [Pecacheu/dualshock#5]
Hey! Thanks for an awesome lib for Dualshock remote.

I just noticed that I **cannot** install the latest version (**3.1.3**) on Linux because of `node-hid` lib and `Windows.h` file.

I can **successfully** install **3.1.1** version (and `node-hid` official package)

I think this is because we need latest updates to support Speaker, but if it's not ready for Linux, maybe we can make them optional, so we can install the latest version successfully?

Cheers 😉

**Comment by r-hede** [comment]
Hi,

I have the same problem.

I cannot install the latest version (**3.1.4**) on **Raspbian 9.6 (stretch)** but the version **3.1.1** works fine.

I get this error: `../main.cc:2:21: fatal error:  Windows.h no such file or directory`

Did you plan to update the library to run on Linux ?

Thank you !

**Comment by ThadeuLuz** [comment]
> I can **successfully** install **3.1.1** version (and `node-hid` official package)

I was having problems with node-hid a Raspberry Pi Zero W I can confirm v3.1.1 works.

**Comment by lefuturiste** [comment]
Same issue here !

**Comment by Pecacheu** [comment]
Same issue as #2
